# this file is a config file.
result0:
  Material: diamond_pickaxe
  Name: test pickaxe
  Amount: 1

  Enchant: mending;1,dig_speed;1
  Lore: test!&!test!&!test
  Unbreak: true
  ItemFlag: hide_unbreakable

recipe0:
  CraftType: 3
  s1:
    Material: diamond
    Amount: 3
    Enchant: mending;1,dig_speed;1

  s2:
    Same: 1
    Change: Material;dirt
  s3:
    Same: 1
    Change: material;sand,amount;10

  s4:
    Same: 1
    Change: enchant;luck~1&lure~1,amount;10

p0:
  material: stone
  amount: 1

  enchant: mending;1,dig_speed;1

result0:
  type: 3
  material: dirt
  amount: 10
  name: test dirt
  enchant: mending;1,dig_speed;1
  lore: this!&!string!&!is a test.
  itemflag: hide_unbreakable
  recipe:
    line0: p0,n,p0
    line1: p0,n,n
    line2: n,n,n