# this file is a config file.
result0:
  Material: diamond_pickaxe
  Enchant: mending,dig_speed
  Enchant_level: 1,1

  Lore: test!&!test!&!test
  Name: test pickaxe
  Unbreak: true
  ItemFlag: hide_unbreakable

recipe0:
  CraftType: 9
  s1:

    Material: diamond
    Amount: 3
    Enchant: mending,dig_speed
    Enchant_level: 1,1
  s2:
    Same: 1
  s3:
    Same: 1
    Change: Material,emerald
  s5:
    Same: 1
    Change: Material,stick&Amount,2
