name: CustomCrafter
version: '1'
main: customcrafter.customcrafter.CustomCrafter
api-version: 1.19
authors: [ SakakiAruka ]
description: custom crafter
website: https://github.com/Sakaki-Aruka
commands:
  customcrafterdebug:
    permission: cc.op

permissions:
  cc.op:
    default: op